name: test-job
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  printing:
    name: my-helloworld-job
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        uses: actions/checkout@v5
      - run: echo "Hello world........"
  
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "testing..........."