name: test-job
on: [push]
jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5
      - run: echo "Hello world........""
  
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - run: echo "testing..........."